// Actors/MutationCommandFactory.swift — resource_browser bounded context
// DDD role: DomainService (value type — stateless, thread-safe)
// ADR refs: ADR-0012 (mutation policy, confirmation token, manifest digest)
//            ADR-0013 (kind catalogue / allowlist)

import CryptoKit
import Foundation

// MARK: - MutationIntent

/// Operator intent expressed in UI terms, before it becomes a typed `MutationCommand`.
///
/// The factory translates each intent variant into the corresponding
/// `MutationCommand` case, embedding confirmation tokens, manifest digests,
/// and credential-redaction where required by ADR-0012.
public enum MutationIntent: Sendable {
    /// Apply a full YAML manifest via server-side apply.
    case applyYAML(manifestYAML: String, targetGVK: GroupVersionKind, namespace: String?, name: String, forceConflicts: Bool)
    /// Update the replica count of a scalable workload.
    case scaleReplicas(targetGVK: GroupVersionKind, namespace: String, name: String, desiredReplicas: Int)
    /// Inject `kubectl.kubernetes.io/restartedAt` to trigger a rollout restart.
    case rolloutRestart(targetGVK: GroupVersionKind, namespace: String, name: String)
    /// Delete a resource. `doubleConfirmed` must be `true` for destructive ops.
    case deleteResource(targetGVK: GroupVersionKind, namespace: String?, name: String, gracePeriodSeconds: Int?, propagationPolicy: PropagationPolicy)
    /// Patch `metadata.labels` with a strategic merge patch.
    case labelPatch(targetGVK: GroupVersionKind, namespace: String?, name: String, labelsToSet: [String: String], labelsToRemove: [String])
    /// Patch `metadata.annotations` with a strategic merge patch.
    case annotationPatch(targetGVK: GroupVersionKind, namespace: String?, name: String, annotationsToSet: [String: String], annotationsToRemove: [String])
}

// MARK: - MutationCommandFactoryError

/// Errors thrown when an intent cannot be translated into a command.
public enum MutationCommandFactoryError: Error, Sendable {
    /// The target GVK is not in the mutation allowlist (ADR-0012 / ADR-0013).
    case gvkNotInAllowlist(GroupVersionKind)
    /// The manifest YAML could not be encoded to UTF-8 for digest computation.
    case manifestEncodingFailed
}

// MARK: - MutationCommandFactory

/// Translates UI intents to typed `MutationCommand` values.
///
/// Embeds the confirmation token provided by the UI layer and computes the
/// SHA-256 manifest digest for apply operations. Redacts annotation values
/// whose keys appear in `config.sensitiveAnnotationKeys` (ADR-0012 §audit).
///
/// `Sendable`-safe: all properties are constants; no mutable state.
public struct MutationCommandFactory: Sendable {

    // MARK: - Properties

    /// Configuration carrying the cluster context ID and sensitive-key deny-list.
    public let config: MutationCommandFactoryConfig

    // MARK: - Initialiser

    /// Creates a factory for the given configuration.
    public init(config: MutationCommandFactoryConfig) {
        self.config = config
    }

    // MARK: - Public API

    /// Translates a `MutationIntent` into a typed `MutationCommand`.
    ///
    /// Embeds `confirmationToken` (generated by the UI confirmation modal) and,
    /// for apply operations, computes the SHA-256 digest of the manifest bytes.
    ///
    /// - Parameters:
    ///   - intent: The operator's expressed intent in UI terms.
    ///   - target: Descriptor of the resource kind targeted by the mutation.
    ///   - confirmationToken: UUIDv7 generated when the confirmation modal appeared.
    /// - Returns: A fully constructed, immutable `MutationCommand`.
    /// - Throws: `MutationCommandFactoryError` if the GVK is not allowed or the
    ///           manifest cannot be encoded.
    public func build(
        intent: MutationIntent,
        target: ResourceDescriptor,
        confirmationToken: UUID
    ) throws -> MutationCommand {
        guard target.supportedVerbs.contains(.patch) || target.supportedVerbs.contains(.delete) else {
            throw MutationCommandFactoryError.gvkNotInAllowlist(target.gvk)
        }

        switch intent {
        case let .applyYAML(yaml, gvk, namespace, name, force):
            let digest = try manifestDigest(yaml)
            let redacted = redactAnnotations(yaml)
            return .applyYAML(ApplyYAML(
                targetGVK: gvk,
                namespace: namespace,
                name: name,
                manifestYAML: redacted,
                manifestDigest: digest,
                forceConflicts: force
            ))

        case let .scaleReplicas(gvk, namespace, name, replicas):
            return .scaleReplicas(ScaleReplicas(
                targetGVK: gvk,
                namespace: namespace,
                name: name,
                desiredReplicas: replicas
            ))

        case let .rolloutRestart(gvk, namespace, name):
            let now = ISO8601DateFormatter().string(from: Date())
            return .rolloutRestart(RolloutRestart(
                targetGVK: gvk,
                namespace: namespace,
                name: name,
                restartedAt: now
            ))

        case let .deleteResource(gvk, namespace, name, grace, policy):
            return .deleteResource(DeleteResource(
                targetGVK: gvk,
                namespace: namespace,
                name: name,
                gracePeriodSeconds: grace,
                propagationPolicy: policy
            ))

        case let .labelPatch(gvk, namespace, name, set, remove):
            return .labelPatch(LabelPatch(
                targetGVK: gvk,
                namespace: namespace,
                name: name,
                labelsToSet: set,
                labelsToRemove: remove
            ))

        case let .annotationPatch(gvk, namespace, name, set, remove):
            return .annotationPatch(AnnotationPatch(
                targetGVK: gvk,
                namespace: namespace,
                name: name,
                annotationsToSet: set,
                annotationsToRemove: remove
            ))
        }
    }

    // MARK: - Private helpers

    /// Computes a lowercase hex SHA-256 digest of the manifest string.
    private func manifestDigest(_ yaml: String) throws -> String {
        guard let data = yaml.data(using: .utf8) else {
            throw MutationCommandFactoryError.manifestEncodingFailed
        }
        let digest = SHA256.hash(data: data)
        return digest.map { String(format: "%02x", $0) }.joined()
    }

    /// Replaces values of sensitive annotation keys with `"<redacted>"`.
    ///
    /// This is a best-effort line-level redaction for YAML. Schema-aware
    /// redaction is applied by the adapter layer before the audit entry is
    /// written (ADR-0012 §audit-log credential invariant).
    private func redactAnnotations(_ yaml: String) -> String {
        var lines = yaml.components(separatedBy: "\n")
        for (i, line) in lines.enumerated() {
            for key in config.sensitiveAnnotationKeys {
                if line.contains(key + ":") {
                    let indent = String(line.prefix(while: { $0 == " " }))
                    lines[i] = "\(indent)\(key): <redacted>"
                    break
                }
            }
        }
        return lines.joined(separator: "\n")
    }
}
