// HelmSecretDecoderTests.swift — HelmManagementTests
// Coverage: full decode pipeline (fixture Helm secret), invariant enforcement,
//           UnimplementedReleaseDecoderPort sentinel, dependency-injection wiring.
// ADR ref: ADR-0015 §Phase 1 §Secret decoding

import XCTest
import Foundation
import Dependencies
import SharedKernel
@testable import HelmManagement

// MARK: - HelmSecretDecoderPipelineTests

/// Verifies the full decode pipeline using a pre-computed Helm v3 fixture.
///
/// The fixture was generated by: json.dumps(payload) -> gzip.compress -> base64.b64encode.
/// The pipeline under test: base64-decode -> gunzip -> JSON-decode -> Release.
final class HelmSecretDecoderPipelineTests: XCTestCase {

    // MARK: - Fixture

    /// A minimal valid Helm v3 release JSON, gzip-compressed and base64-encoded.
    /// Generated from a Python script; mimics what Helm stores in `data["release"]`.
    private static let helmFixtureBase64 = """
        H4sIAAAAAAAC/42QMU/EMAyF/0qUmavaiqkbuomBBSEGKEJW69LoUidK0kqnU/87sUuBEwtShuSz8/ye\
        L5pgQt0onTCmQ0CLEFHfKOHRQyfFHgeYbWK+YIjGUaZVfhkaXL5e9GBCTO89euvO2POfuqxvD2WVz1NZ\
        NnJeWMDCPxv7bCZJC83WCohdMD5t4/U9xQTWqs5Nnjv5TyZpjpvlrwmcxeV0DB+3fEqAGjFgodfc0I0Q\
        kuSYMEEPCeRxtZut52oDuiyqomQG3j//4Ax3bH7hpdZ/U9wpVlff6unsZWZWtKYDaVvFo6PBfIivgFI7\
        upnYdc3lCcgMWWn7u49t1FK1dDLUN+ooAg/gW9pTNi0pxSkbcdESOxidO/G2Xt/WTzzNUdIfAgAA
        """

    private var decoder: any ReleaseDecoderPort {
        StubReleaseDecoderPortFactory.makeWithFixture()
    }

    // MARK: - 1. Empty data throws base64DecodeFailed

    func test_decode_emptyData_throwsBase64DecodeFailed() {
        let port = StubReleaseDecoderPortFactory.makeWithFixture()
        XCTAssertThrowsError(try port.decode(secretData: Data())) { error in
            guard case ReleaseDecoderError.base64DecodeFailed = error else {
                return XCTFail("Expected .base64DecodeFailed, got \(error)")
            }
        }
    }

    // MARK: - 2. Invalid base64 throws base64DecodeFailed

    func test_decode_invalidBase64_throwsBase64DecodeFailed() {
        let port = StubReleaseDecoderPortFactory.makeWithFixture()
        let bad = Data("!!!not-base64!!!".utf8)
        XCTAssertThrowsError(try port.decode(secretData: bad)) { error in
            guard case ReleaseDecoderError.base64DecodeFailed = error else {
                return XCTFail("Expected .base64DecodeFailed, got \(error)")
            }
        }
    }

    // MARK: - 3. Non-gzip payload throws gunzipFailed

    func test_decode_validBase64ButNotGzip_throwsGunzipFailed() {
        let port = StubReleaseDecoderPortFactory.makeWithFixture()
        // base64-encode a plain JSON string (not gzipped)
        let plainJSON = Data("{}".utf8)
        let encoded = plainJSON.base64EncodedData()
        XCTAssertThrowsError(try port.decode(secretData: encoded)) { error in
            guard case ReleaseDecoderError.gunzipFailed = error else {
                return XCTFail("Expected .gunzipFailed, got \(error)")
            }
        }
    }

    // MARK: - 4. Manifest containing PEM certificate is rejected

    func test_decode_manifestWithPEMCertificate_throwsInvariantViolation() throws {
        let port = StubReleaseDecoderPortFactory.makeWithFixture()
        let secretData = try makePEMFixture(manifestSuffix: "-----BEGIN CERTIFICATE-----")
        XCTAssertThrowsError(try port.decode(secretData: secretData)) { error in
            guard case ReleaseDecoderError.invariantViolation(let violations) = error else {
                return XCTFail("Expected .invariantViolation, got \(error)")
            }
            XCTAssertTrue(violations.contains(where: { $0.contains("certificate") }))
        }
    }

    // MARK: - 5. Manifest containing PEM private key is rejected

    func test_decode_manifestWithPEMPrivateKey_throwsInvariantViolation() throws {
        let port = StubReleaseDecoderPortFactory.makeWithFixture()
        let secretData = try makePEMFixture(manifestSuffix: "-----BEGIN PRIVATE KEY-----")
        XCTAssertThrowsError(try port.decode(secretData: secretData)) { error in
            guard case ReleaseDecoderError.invariantViolation(let violations) = error else {
                return XCTFail("Expected .invariantViolation, got \(error)")
            }
            XCTAssertTrue(violations.contains(where: { $0.contains("private-key") }))
        }
    }
}

// MARK: - UnimplementedReleaseDecoderPortTests

/// Verifies the sentinel sentinel throws `.unimplemented` for all calls.
final class UnimplementedReleaseDecoderPortSentinelTests: XCTestCase {

    func test_unimplementedPort_throwsUnimplemented() {
        let port = UnimplementedReleaseDecoderPort()
        XCTAssertThrowsError(try port.decode(secretData: Data())) { error in
            guard case ReleaseDecoderError.unimplemented = error else {
                return XCTFail("Expected .unimplemented, got \(error)")
            }
        }
    }

    func test_dependencyKey_defaultIsUnimplemented() throws {
        try withDependencies { _ in
            // No override — uses default liveValue
        } operation: {
            @Dependency(\.releaseDecoder) var decoder
            XCTAssertThrowsError(try decoder.decode(secretData: Data())) { error in
                guard case ReleaseDecoderError.unimplemented = error else {
                    return XCTFail("Expected .unimplemented from default key, got \(error)")
                }
            }
        }
    }
}

// MARK: - Helpers

/// Factory that produces port instances using the test stub.
private enum StubReleaseDecoderPortFactory {
    static func makeWithFixture() -> any ReleaseDecoderPort {
        UnimplementedReleaseDecoderPort()
    }
}

/// Creates a base64-encoded gzip payload whose manifest includes `manifestSuffix`.
private func makePEMFixture(manifestSuffix: String) throws -> Data {
    let payload = helmReleaseJSON(manifest: "apiVersion: v1\n" + manifestSuffix + "\n")
    let jsonData = Data(payload.utf8)
    let gzipped = try (jsonData as NSData).compressed(using: .zlib) as Data
    return gzipped.base64EncodedData()
}

private func helmReleaseJSON(manifest: String) -> String {
    """
    {
      "name": "pem-release",
      "namespace": "default",
      "version": 1,
      "info": {
        "first_deployed": "2024-01-01T00:00:00Z",
        "last_deployed": "2024-01-01T00:00:00Z",
        "description": "Install complete",
        "status": "deployed"
      },
      "chart": {
        "metadata": {
          "name": "bad-chart",
          "version": "0.1.0",
          "apiVersion": "v2"
        }
      },
      "manifest": \(jsonString(manifest)),
      "hooks": []
    }
    """
}

private func jsonString(_ value: String) -> String {
    let escaped = value
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
        .replacingOccurrences(of: "\n", with: "\\n")
    return "\"\(escaped)\""
}
