// Domain/ClusterDescriptor.swift — cluster_connectivity bounded context
// DDD role: ValueObject
// ADR ref: ADR-0055 (Cloud provider cluster discovery)

import Foundation

// MARK: - ClusterDescriptor

/// Provider-agnostic descriptor for a cluster surfaced by
/// `CloudClusterDiscoveryPort`.
///
/// The descriptor carries enough information to render the cluster in the
/// import sheet and to materialise a kubeconfig entry. It is intentionally
/// not the full domain `Cluster` aggregate — that emerges after the
/// kubeconfig entry has been merged into the operator's kubeconfig source
/// and re-parsed by `ClusterAssembler`.
public struct ClusterDescriptor: Sendable, Hashable, Codable, Identifiable {
    /// Provider-native identifier (ARN, resource id, GKE cluster id).
    /// Stable across discovery calls.
    public let id: String

    /// Operator-facing label rendered in the import sheet.
    public let displayName: String

    /// Provider responsible for this descriptor.
    public let provider: CloudProvider

    /// AWS region or GCP location. `nil` for Azure (resource group is used
    /// for naming but is not a geographic coordinate at this layer).
    public let region: String?

    /// Cluster management API endpoint. Always HTTPS.
    public let endpoint: URL

    /// Cluster CA certificate in PEM format. May be empty for private
    /// clusters where the CA is not part of the public discovery response
    /// (the operator must supply the CA out-of-band).
    public let caCertificatePEM: String

    /// Provider-specific pass-through metadata (Kubernetes version, tags,
    /// resource group, project id, etc.). Strict subset documented by the
    /// adapter that produced the descriptor.
    public let providerMetadata: [String: String]

    public init(
        id: String,
        displayName: String,
        provider: CloudProvider,
        region: String?,
        endpoint: URL,
        caCertificatePEM: String,
        providerMetadata: [String: String] = [:]
    ) {
        self.id = id
        self.displayName = displayName
        self.provider = provider
        self.region = region
        self.endpoint = endpoint
        self.caCertificatePEM = caCertificatePEM
        self.providerMetadata = providerMetadata
    }
}

// MARK: - KubeconfigEntry

/// Triple of cluster + context + user that maps to a kubeconfig file entry,
/// ready for merge into the operator's kubeconfig aggregate.
///
/// Distinct from `Kubeconfig`, which represents the whole aggregate. A
/// `KubeconfigEntry` is the smallest "addable" unit produced by discovery
/// or clipboard import flows.
public struct KubeconfigEntry: Sendable, Hashable, Codable, Identifiable {
    /// Stable identifier for the import attempt. UUID is generated by the
    /// adapter; persisted only if the entry survives operator confirmation.
    public let id: UUID

    /// Cluster entry to be written to the kubeconfig file.
    public let cluster: KubeconfigCluster

    /// Context entry referencing `cluster.name` and `user.name`.
    public let context: KubeconfigContext

    /// User entry carrying the exec block (provider-specific token plugin).
    public let user: KubeconfigUser

    public init(
        id: UUID = UUID(),
        cluster: KubeconfigCluster,
        context: KubeconfigContext,
        user: KubeconfigUser
    ) {
        self.id = id
        self.cluster = cluster
        self.context = context
        self.user = user
    }
}

// MARK: - DiscoveryWarning

/// Non-fatal advisory emitted by a discovery adapter alongside successful
/// results. Surfaced to the operator via the toast notification stream.
///
/// Examples:
/// - AWS adapter could not call `ec2:DescribeRegions`; fell back to the
///   static partition region list.
/// - Azure private cluster has no public CA certificate; entry will
///   require operator-supplied CA before connection succeeds.
/// - GCP project enumeration paged out before reaching its `nextPageToken`;
///   later clusters may be missing.
public struct DiscoveryWarning: Sendable, Hashable, Codable, Identifiable {
    public enum Code: String, Sendable, Codable {
        case awsRegionListUnavailable
        case azurePrivateClusterCAMissing
        case gcpProjectEnumerationTruncated
        case clusterEndpointUnreachable
        case partialFailure
    }

    public let id: UUID
    public let provider: CloudProvider
    public let code: Code
    public let message: String

    public init(
        id: UUID = UUID(),
        provider: CloudProvider,
        code: Code,
        message: String
    ) {
        self.id = id
        self.provider = provider
        self.code = code
        self.message = message
    }
}
